### ISSUE TITLE
Deprecation warnings for string.character in Swift 4

### ISSUE THREAD

**Issue by frankdilo** [ArtSabintsev/Guitar#20]
Hi, 
I am using Guitar with Swift 4 and getting the following deprecation warnings due to the character view of strings now being deprecated (strings in Swift 4 are collection types again).

This should be easy to solve, would you accept a PR for this?

<img width="414" alt="screenshot 2018-01-01 19 41 01" src="https://user-images.githubusercontent.com/715405/34470176-e55b5f88-ef2b-11e7-89b3-b11221672e7a.png">

**Comment by ArtSabintsev** [comment]
Hey! Somehow I missed this in my notifications. There is a Swift 4 branch on master (v0.3.0). Have you tried that?
