### ISSUE TITLE
API inconsistency

### ISSUE THREAD

**Issue by svachmic** [ArtSabintsev/Guitar#4]
Hi, pretty nice lib you've got there - great work!

I would just suggest a change in outputs of two methods that seem to be colliding in consistency:

```
let string = "hello world"
string.isLowercased() // False

let string = "HELLO WORLD"
string.isUpppercased() // True
```

It's quite hard to program around such cases where the statement holds for one type (uppercase), but not for the other (lowercase). Especially when you'd expect `true` from both. I know there are language constraints, but the API is then quite inconsistent.

Cheers!

**Comment by ArtSabintsev** [comment]
Sure, I agree. I need to build one API around splitting words, and then I can override the language constraint, plus fix and build a lot more APIs.

It's on my to-do list. The API will be unstable for a while to come, but I appreciate any/all issues/PRs.

**Comment by ArtSabintsev** [comment]
I'm beginning to address this in #7. A future PR, hopefully this weekend, will address the API inconsistencies in a few places.

In that PR, I implemented a few Regex methods that should make it easier to deal with all the manipulation functions, and in the case of capitalized, create a new one all together.

**Comment by ArtSabintsev** [comment]
Closing this issue for now, as this is a known issue and due to the alpha stage of the API.

**Comment by ArtSabintsev** [comment]
This was fixed in one of the latest releases.
