### ISSUE TITLE
[Feature]: What features are needed for Regex implementation?

### ISSUE THREAD

**Issue by tkmu** [ArtSabintsev/Guitar#6]
I want to contribute and eager to know what kind of features you are looking for to develop in Regex.

**Comment by ArtSabintsev** [comment]
Hey, @nefarianblack!

Thanks for the offer to help. I have a feeling this might not need to be done as NSRegularExpression seems to be exposed on the OSS version of Swift's Foundation library:

https://github.com/apple/swift-corelibs-foundation/blob/fca0a34ab9cb017b085457046856d9dd73c03384/Foundation/NSRegularExpression.swift

However, if you still want to try,  I'm envisioning a Parser that works with the existing Array, String, and Character APIs. Feel free to get started on that if you'd like!

**Comment by ArtSabintsev** [comment]
Alright, did some research and testing. NSRegularExpression is indeed supported on both macOS and Linux. I will therefore add some syntactic sugary code on top of it, which I already have stored locally in another file.

Thanks for the offer - closing this issue.

**Comment by tkmu** [comment]
Sure! 🤘
Excited for that update on regex!

**Comment by ArtSabintsev** [comment]
Me too. Probably later tonight!

**Comment by ArtSabintsev** [comment]
Started working on it: https://github.com/ArtSabintsev/Guitar/pull/7

It'll be done tomorrow.

**Comment by ArtSabintsev** [comment]
Merged it in. 

https://github.com/ArtSabintsev/Guitar/blob/master/Sources/GuitarRegex.swift
