### ISSUE TITLE
Cocoapods Installation failure

### ISSUE THREAD

**Issue by NerdGr8** [ArtSabintsev/Guitar#8]
Tried installing the library through cocoapods and it fails with the following error 

`[!] Unable to find a specification for `Guitar``

**Comment by ArtSabintsev** [comment]
Hmm, can't reproduce that.

- What version of CocoaPods are you using?
- What version of Guitar are you trying to install?

This what worked for me `pod 'Guitar'`.

**Comment by ArtSabintsev** [comment]
Going to close this issue, but feel free to comment, and I'll follow up.
