### ISSUE TITLE
From snake case to slug case

### ISSUE THREAD

**Issue by onmyway133** [ArtSabintsev/Guitar#9]
Hi, nice library 👍 

Just a question, how can I transform from case A to case B, like snake case to slug case `hello_world` -> `hello-world`? or from camel case to snake case, like `helloWorld` -> `hello-world`?

**Comment by ArtSabintsev** [comment]
hey - thanks!

Library is still under works. At the moment, I'm implementing some syntactic-sugar regex functions that will allow me to do these transformations more seamlessly. (see #7)

At present, the following happens:

```
        let hw = "hello_world"
        print(hw.slugCased()) // hello-world (correct)
        print(hw.camelCased()) // helloworld (incorrect)
```

Some of this should be addressed today, and the rest by this weekend.

**Comment by ArtSabintsev** [comment]
Going to close this issue as this is a WIP. 

End goal is to be able to swap from one case to another without issue, and the new regex system I've begun building out should make that pretty simple to do.

**Comment by onmyway133** [comment]
Looking forward 👍

**Comment by ArtSabintsev** [comment]
I think it should be live already. Try it out with v0.0.9. Will have more improvements over the weekend. I actually have a lot planned :)

**Comment by ArtSabintsev** [comment]
Fixed it.

All these tests pass: https://github.com/ArtSabintsev/Guitar/blob/master/GuitarExample/GuitarExampleTests/GuitarCaseTests.swift#L65-L92

Here is the code that enabled it:

https://github.com/ArtSabintsev/Guitar/blob/master/Sources/GuitarCase.swift#L118-L141

**Comment by onmyway133** [comment]
@ArtSabintsev looks great. This is very handy when dealing with different json styles

**Comment by ArtSabintsev** [comment]
Glad you think so! Enjoy!
